home/urls.py
from django.urls import path
from .views import *

app_name = "home"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("bucket/", BucketHomeView.as_view(), name="bucket"),
    path(
        "product-detail/<int:product_id>/<slug:product_slug>",
        ProductDetailView.as_view(),
        name="product-detail",
    ),
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("home.urls", namespace="home")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ("name",)
        verbose_name_plural = "categories"

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, related_name="products"
    )
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)
    image = models.ImageField(
        upload_to="products/%Y/%B/%d/",
        height_field=None,
        width_field=None,
        max_length=None,
    )
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=5, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ("name",)

    def __str__(self):
        return self.name

home/views.py
from django.shortcuts import render
from django.http.request import HttpRequest
from django.views import View
from .models import Product
from .tasks import all_bucket_objects_tasks

# Create your views here.


class HomeView(View):
    template_name = "home/home.html"

    def get(self, request: HttpRequest):
        products = Product.objects.filter(available=True)
        return render(request, self.template_name, {"products": products})


class ProductDetailView(View):
    template_name = "home/detail.html"

    def get(self, request, *args, **kwargs):
        product_id, product_slug = kwargs["product_id"], kwargs["product_slug"]
        product = Product.objects.get(pk=product_id, slug=product_slug)
        return render(request, self.template_name, {"product": product})


class BucketHomeView(View):
    template_name = "home/bucket.html"

    def get(self, request, *args, **kwargs):
        objects = all_bucket_objects_tasks()
        return render(request, self.template_name, {"objects": objects})

home/templates/home/bucket.html
{% extends "base.html" %}

{% block content %}
    <div class="container-fluid mt-3">
        <table class="table table-dark">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Object Size</th>
                <th scope="col">Download Link</th>
                <th scope="col">Delete Link</th>
            </tr>
            </thead>
            <tbody>
                {% for obj in objects %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{ obj.Key}}</td>
                        <td>{{ obj.Size|filesizeformat }}</td>
                        <td>Download</td>
                        <td>Delete</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock  %}

home/templates/home/detail.html
{% extends "base.html" %}

{% block content %}
    <!-- content -->
<section class="py-5">
    <div class="container">
      <div class="row gx-5">
        <aside class="col-lg-6">
          <div class="border rounded-4 mb-3 d-flex justify-content-center">
            <a data-fslightbox="mygalley" class="rounded-4" target="_blank" data-type="image" href="{{ product.image.url }}">
              <img style="max-width: 100%; max-height: 100vh; margin: auto;" class="rounded-4 fit" src="{{ product.image.url }}" />
            </a>
          </div>
        </aside>
        <main class="col-lg-6">
          <div class="ps-lg-3">
            <h4 class="title text-dark">
              {{ product.name }}
            </h4>
  
            <p>
                {{ product.description }}
            </p>
  
            <div class="row">
              <dt class="col-3">Price:</dt>
              <dd class="col-9">${{ product.price }}</dd>

            </div>
  
            <hr />
            </div>
            <a href="#" class="btn btn-primary shadow-0"> <i class="me-1 fa fa-shopping-basket"></i> Add to cart </a>
          </div>
        </main>
      </div>
    </div>
  </section>
  <!-- content -->
{% endblock  %}

home/templates/home/home.html
{% extends "base.html" %}
{% load static %}

{% block extra_headers %}
    <link rel="stylesheet" href="{% static 'home/css/style.css' %}">
{% endblock  %} 

{% block header %}
    <h3>Welcome To My Shop</h3>
{% endblock  %}

{% block content %}
    {% for product in products %}
        <div class="card" style="width: 18rem;">
            <img src="{{ product.image.url }}" class="card-img-top" alt="...">
            <div class="card-body">
                <a href="{% url "home:product-detail" product.id product.slug %}"><h5 class="card-title">{{ product.name }}</h5></a>
                <a href="#" class="btn btn-primary">Add To Card</a>
            </div>
        </div>
    {% endfor %}
{% endblock %}