accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("register/", views.UserRegisterView.as_view(), name="user-register"),
    path("login/", views.LoginView.as_view(), name="user-login"),
    path("logout/", views.LogoutView.as_view(), name="user-logout"),
    path("verify/", views.UserVerifyCodeView.as_view(), name="user-verify-code"),
]

home/urls.py
from django.urls import path
from .views import *

app_name = "home"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("bucket/", BucketHomeView.as_view(), name="bucket"),
    path(
        "product-detail/<int:product_id>/<slug:product_slug>",
        ProductDetailView.as_view(),
        name="product-detail",
    ),
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("home.urls", namespace="home")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/inc/messages.html
{% if messages %}
    {% for msg in messages %}
        <p class="alert alert-{{msg.tags}}">{{ msg }}</p>
    {% endfor %}
{% endif %}

templates/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <div class="navbar-nav">
            <a class="nav-link active" href="{% url "home:home" %}">Home</a>
            {% if request.user.is_authenticated %}
                {% if request.user.is_admin %}
                    <a class="nav-link active" href="{% url "home:bucket" %}">Bucket</a>
                {% endif %}
                <a class="nav-link active" href="{% url "accounts:user-logout" %}">Logout</a>
            {% else %}
                <a class="nav-link active" href="{% url "accounts:user-register" %}">Register</a>
                <a class="nav-link active" href="{% url "accounts:user-login" %}">Login</a>
            {% endif %}
            
        </div>
        {% if request.user.is_authenticated %}
        <span class="navbar-text text-left">
            {{request.user}}
        </span>
        {% endif %}

    </div>
</nav>